version: '3'

services: 
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes: 
      - /var/app/node_modules
      - .:/var/app/
  react-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes: 
      - /var/app/node_modules
      - .:/var/app/